/* Generated By:JJTree: Do not edit this line. ./ExpressionParserTreeConstants.java */

package wvustat.math.expression;

public interface ExpressionParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTLOGICALEXP = 1;
  public int JJTCOMPARISONEXP = 2;
  public int JJTADDICTIVEEXP = 3;
  public int JJTMULTIPLICATIVEEXP = 4;
  public int JJTUNARYEXP = 5;
  public int JJTEXPONENTIALEXP = 6;
  public int JJTLITERALEXP = 7;
  public int JJTFUNCEXP = 8;
  public int JJTVARIABLE = 9;


  public String[] jjtNodeName = {
    "void",
    "LogicalExp",
    "ComparisonExp",
    "AddictiveExp",
    "MultiplicativeExp",
    "UnaryExp",
    "ExponentialExp",
    "LiteralExp",
    "FuncExp",
    "Variable",
  };
}
