/*
 * ParamInitializer.java
 *
 * Created on February 22, 2002, 11:46 AM
 */

package wvustat.math.UI;

import java.awt.*;
import java.util.Vector;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author  James Harner
 * @version 
 */
public class ParamInitializer extends JDialog implements java.awt.event.ActionListener{
    private Vector params;
    private JTextField[] inputs;
    private double[] values;
    private boolean isCanceled=false;
    /** Creates new form ParamInitializer */
    public ParamInitializer(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        
        initComponents ();
        pack ();        
    }
    
    public ParamInitializer(Frame parent, Vector params){
        super(parent, true);
        this.params=params;
        values=new double[params.size()];
        initComponents();
        pack();
        
        if(parent.isShowing()){
            Dimension d1=parent.getPreferredSize();
            Point p=parent.getLocationOnScreen();
            Dimension d2=this.getPreferredSize();
            
            this.setLocation(p.x+d1.width/2-d2.width/2, p.y+d1.height/2-d2.height/2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {
        JLabel label1 = new JLabel();
        JLabel label2 = new JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog();
            }
        }
        );
        
        label1.setText("Parameter");
        label1.setFont(new java.awt.Font ("Dialog", 1, 12));
        
        JLabel prompt1=new JLabel("Please specify the initial values for");
        JLabel prompt2=new JLabel("the following parameters in the formula.");
        
        JPanel contentPane=new JPanel();
        contentPane.setLayout(new GridBagLayout());
        
        contentPane.add(prompt1, new GridBagConstraints(0,0,0,1,0,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        contentPane.add(prompt2, new GridBagConstraints(0,1,0,1,0,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        contentPane.add(label1, new GridBagConstraints(0,2,-1,1,0.5,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        
        
        label2.setText("Value");
        label2.setFont(new java.awt.Font ("Dialog", 1, 12));
        
        contentPane.add(label2, new GridBagConstraints(1,2,0,1,0.5,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        
        inputs=new JTextField[params.size()];
        for(int i=0;i<params.size();i++){
            JLabel jl=new JLabel(params.elementAt(i).toString()+" =");
            contentPane.add(jl, new GridBagConstraints(0,i+3,-1,1,0.5,0,GridBagConstraints.WEST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
            JTextField jt=new JTextField(10);
            contentPane.add(jt, new GridBagConstraints(1,i+3,0,1,0.5,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
            inputs[i]=jt;
        }
        
        JPanel buttonPanel=new JPanel();
        buttonPanel.setLayout(new GridLayout(1,2,30,8));
        JButton okButton=new JButton("Ok");
        JButton cancelButton=new JButton("Cancel");
        
        okButton.addActionListener(this);
        cancelButton.addActionListener(this);
        
        buttonPanel.add(cancelButton);
        buttonPanel.add(okButton);
        
        contentPane.add(buttonPanel, new GridBagConstraints(0,params.size()+3,0,0,1.0,0,GridBagConstraints.CENTER,GridBagConstraints.HORIZONTAL,new Insets(20,2,2,2),6,0));
        contentPane.setBorder(new EmptyBorder(8,20,8,20));
        this.setContentPane(contentPane);
    }

    /** Closes the dialog */
    private void closeDialog() {
        setVisible (false);
        dispose ();
    }

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        Vector v=new Vector();
        v.addElement("A1");
        v.addElement("A2");
        v.addElement("A3");
        new ParamInitializer (new Frame(), v).show ();
    }

    public void actionPerformed(java.awt.event.ActionEvent p1) {
        String cmd=p1.getActionCommand();
        
        if(cmd.equals("Ok")){
            for(int i=0;i<values.length;i++){
                try{
                    values[i]=new Double(inputs[i].getText()).doubleValue();
                }
                catch(NumberFormatException err){
                    WarningDialog.showWarning((Frame)getParent(),"Invalid input for parameter "+params.elementAt(i).toString());
                    return;
                }
            }
        }
        else{
            isCanceled=true;
        }
        
        setVisible(false);
        dispose();
    }
    
    public double[] getValues(){
        if(!isCanceled)
            return values;
        else 
            return null;
    }    
    
    public boolean isCanceled(){
        return isCanceled;
    }

}
