/*
 * ReportDialog.java
 *
 * Created on March 4, 2002, 2:00 PM
 */

package wvustat.math.UI;

import java.awt.*;
import java.awt.event.*;
import java.util.Hashtable;
import java.util.Enumeration;
import java.text.NumberFormat;

import wvustat.plotUtil.MyGridBagConstraints;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author  Hengyi Xue
 * @version 
 */
public class ReportDialog extends JDialog implements ActionListener{

    private Hashtable paramTable;
    private String formula;
    private double SD;
    /** Creates new form ParamInitializer */
   
    public ReportDialog(Frame parent, String formula, Hashtable paramTable, double SD){
        super(parent, true);
        this.formula=formula;
        this.paramTable=paramTable;
        this.SD=SD;
        initComponents();
        pack();
        
        if(parent.isShowing()){
            Dimension d1=parent.getPreferredSize();
            Point p=parent.getLocationOnScreen();
            Dimension d2=this.getPreferredSize();
            
            this.setLocation(p.x+d1.width/2-d2.width/2, p.y+d1.height/2-d2.height/2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {

        JLabel label1 = new JLabel();

        label1.setText("Function");
        label1.setFont(new java.awt.Font ("Dialog", Font.BOLD, 12));
        
        JLabel prompt1=new JLabel(formula);
        JLabel prompt2=new JLabel("Regression Results:");
        prompt2.setFont(new Font("Dialog", Font.BOLD, 12));
        
        JPanel contentPane=new JPanel();
        contentPane.setLayout(new GridBagLayout());
        
        contentPane.add(label1, new MyGridBagConstraints(0,0,0,1,0,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        contentPane.add(prompt1, new MyGridBagConstraints(0,1,0,1,0,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        contentPane.add(prompt2, new MyGridBagConstraints(0,2,-1,1,0.5,0,GridBagConstraints.EAST,GridBagConstraints.HORIZONTAL,new Insets(20,2,2,2),0,0));
        
        NumberFormat nf=NumberFormat.getInstance();
        nf.setMaximumFractionDigits(4);
        
        int i=0;
        for(Enumeration enum1=paramTable.keys();enum1.hasMoreElements();){
            Object key=enum1.nextElement();
            JLabel jl=new JLabel(key.toString()+"= "+nf.format(((Double)paramTable.get(key)).doubleValue()));
            contentPane.add(jl, new MyGridBagConstraints(0,i+3,0,1,0,0,GridBagConstraints.WEST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
            i++;
        }
        
        contentPane.add(new JLabel("Standard Deviation = "+nf.format(SD)+"            "), new MyGridBagConstraints(0,paramTable.size()+3,0,1,0,0,GridBagConstraints.WEST,GridBagConstraints.HORIZONTAL,new Insets(2,2,2,2),0,0));
        
        JPanel buttonPanel=new JPanel();
        buttonPanel.setLayout(new GridLayout(1,1,8,8));
        JButton okButton=new JButton("Ok");
        
        okButton.addActionListener(this);
        
        buttonPanel.add(okButton);
        
        contentPane.add(buttonPanel, new MyGridBagConstraints(0,paramTable.size()+4,0,0,1.0,0,GridBagConstraints.CENTER,GridBagConstraints.NONE,new Insets(20,2,2,2),6,0));
        this.setContentPane(contentPane);
        contentPane.setBorder(new EmptyBorder(8,20,8,20));

    }

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        Hashtable table=new Hashtable();
        table.put("a", new Double(1.23));
        table.put("b", new Double(0.55));
        
        new ReportDialog (new Frame(), "y=a*exp(b*x)",table,12.456).show ();
    }

    public void actionPerformed(java.awt.event.ActionEvent p1) {
  
        setVisible(false);
        dispose();
    }
    

}