/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
package wvustat.math.expression;

public interface ExpressionParserConstants {

  int EOF = 0;
  int NUM_LITERAL = 5;
  int BOOL_LITERAL = 6;
  int EXPONENT = 7;
  int STRING_LITERAL = 8;
  int IDENTIFIER = 9;
  int LETTER = 10;
  int DIGIT = 11;
  int GT = 12;
  int LT = 13;
  int EQ = 14;
  int GE = 15;
  int LE = 16;
  int NE = 17;
  int AND = 18;
  int OR = 19;
  int NOT = 20;
  int PLUS = 21;
  int MINUS = 22;
  int MUL = 23;
  int DIV = 24;
  int POWER = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUM_LITERAL>",
    "<BOOL_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
